"""added converted type to convertion file table

Revision ID: 03bb640a8e9c
Revises: 7dd3b6beec9f
Create Date: 2026-06-04 10:29:55.234000
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "03bb640a8e9c"
down_revision: Union[str, None] = "7dd3b6beec9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_conversions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("converted_file_path", sa.String(), nullable=False),
        sa.Column("converted_mime_type", sa.String(length=100), nullable=False),
        sa.Column("converted_to_extension", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_conversions")
    # ### end Alembic commands ###
