"""create files table

Revision ID: 5c915e0dbb73
Revises: b2c3d4e5f6a7
Create Date: 2026-05-28 08:48:57.131631
"""

from typing import Sequence, Union


revision: str = "5c915e0dbb73"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
