"""remove lang column from workspaces

Revision ID: 62f714cc3741
Revises: f020c2b5e5e5
Create Date: 2026-05-21 10:03:34.524595
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62f714cc3741'
down_revision: Union[str, None] = 'f020c2b5e5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'lang')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
