"""Added type of file on the file table and added converted type to convertion file table

Revision ID: 7dd3b6beec9f
Revises: c4303f4a4770
Create Date: 2026-06-04 09:37:52.666556
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "7dd3b6beec9f"
down_revision: Union[str, None] = "c4303f4a4770"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "files", sa.Column("file_extension", sa.String(length=20), nullable=True)
    )
    op.execute(
        "UPDATE files SET file_extension = LOWER(SUBSTRING(original_filename FROM '\\.([^.]+)$')) WHERE file_extension IS NULL"
    )
    op.alter_column("files", "file_extension", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("files", "file_extension")
    # ### end Alembic commands ###
