"""swap unique constraint from slug to storage_key

Revision ID: 7fe1326d9699
Revises: 771b30272481
Create Date: 2026-05-21 08:21:42.850601
"""

from typing import Sequence, Union

from alembic import op


revision: str = "7fe1326d9699"
down_revision: Union[str, None] = "771b30272481"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("workspaces_slug_key"), "workspaces", type_="unique")
    op.create_unique_constraint(None, "workspaces", ["storage_key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workspaces", type_="unique")
    op.create_unique_constraint(
        op.f("workspaces_slug_key"),
        "workspaces",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
