"""added type of file in file table and created converted_file table

Revision ID: c4303f4a4770
Revises: 3a8bf6c77691
Create Date: 2026-06-04 09:34:08.101663
"""

from typing import Sequence, Union


revision: str = "c4303f4a4770"
down_revision: Union[str, None] = "3a8bf6c77691"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
