"""create files table gen

Revision ID: c677b7c1ccf2
Revises: 5c915e0dbb73
Create Date: 2026-05-28 09:07:07.307023
"""

from typing import Sequence, Union


revision: str = "c677b7c1ccf2"
down_revision: Union[str, None] = "5c915e0dbb73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
